import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ms" | "ta" | "zh";
export type FontSize = "small" | "medium" | "large";

interface Settings {
  language: Language;
  fontSize: FontSize;
  darkMode: boolean;
  notifications: boolean;
  highContrast: boolean;
}

interface SettingsContextType {
  settings: Settings;
  updateSettings: (partial: Partial<Settings>) => void;
  t: (key: string) => string;
}

const DEFAULT_SETTINGS: Settings = {
  language: "en",
  fontSize: "medium",
  darkMode: false,
  notifications: true,
  highContrast: false,
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.dashboard": "Dashboard",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.faq": "FAQ",
    "nav.contactUs": "Contact Us",
    // Dashboard
    "nav.newApplication": "New Application",
    "nav.paymentSetup": "Payment Setup",
    "nav.trackStatus": "Track Status",
    "nav.transactions": "Transactions",
    "dashboard.welcome": "Assalamualaikum",
    "dashboard.subtitle": "Manage your Skim Pintar membership and applications.",
    "dashboard.yourApplications": "Your Applications",
    "dashboard.noApplications": "No applications yet",
    "dashboard.applyNow": "Apply Now",
    "dashboard.aboutSkimPintar": "About Skim Pintar",
    "dashboard.applyViaSingpass": "Apply via Singpass",
    "dashboard.setUpCard": "Set up card deductions",
    "dashboard.viewStatus": "View application status",
    "dashboard.viewPayments": "View payment history",
    "dashboard.cancelApplication": "Cancel Application",
    "dashboard.cancelConfirm": "Are you sure you want to cancel this application? This action cannot be undone. The cancelled application will remain in your records.",
    "dashboard.keepApplication": "Keep Application",
    "dashboard.yesCancel": "Yes, Cancel",
    "dashboard.cancelling": "Cancelling...",
    // Plans
    "plan.pintar": "Pintar",
    "plan.pintarPlus": "Pintar Plus",
    "plan.pintarPrice": "Pintar ($5/month)",
    "plan.pintarPlusPrice": "Pintar Plus ($20/month)",
    "plan.pintarDesc": "Free funeral services for the donor in the event of death.",
    "plan.pintarPlusDesc": "Complimentary funeral services for the donor and immediate family living under one address.",
    "plan.recommended": "Recommended",
    "plan.benefits": "Benefits include:",
    // Apply
    "apply.title": "New Application",
    "apply.subtitle": "Skim Pintar Registration",
    "apply.choosePlan": "Choose Your Plan",
    "apply.howRegister": "How would you like to register?",
    "apply.singpassDesc": "Use Singpass for faster registration with auto-filled details.",
    "apply.loginSingpass": "Login with Singpass",
    "apply.autoFill": "Auto-fill your details with MyInfo",
    "apply.manualEntry": "Manual Entry",
    "apply.manualDesc": "Fill in your details manually",
    "apply.connectingSingpass": "Connecting to Singpass",
    "apply.retrievingData": "Retrieving your MyInfo data...",
    "apply.myInfoLoaded": "MyInfo data loaded. Please verify your details.",
    "apply.fillDetails": "Please fill in your details below.",
    "apply.fullName": "Full Name (as in NRIC)",
    "apply.nric": "NRIC Number",
    "apply.dob": "Date of Birth",
    "apply.phone": "Phone Number",
    "apply.email": "Email",
    "apply.address": "Address",
    "apply.selectedPlan": "Selected Plan",
    "apply.back": "Back",
    "apply.submit": "Submit Application",
    "apply.submitting": "Submitting...",
    // Status
    "status.title": "Application Status",
    "status.subtitle": "Track your Skim Pintar applications",
    "status.noApplications": "No Applications",
    "status.noApplicationsDesc": "You haven't submitted any applications yet.",
    "status.submitted": "Submitted",
    "status.underReview": "Under Review",
    "status.paymentVerified": "Payment Verified",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.cancelled": "Cancelled",
    "status.cancelledOn": "Cancelled on",
    "status.cancelApplication": "Cancel Application",
    // Payment
    "payment.title": "Payment Setup",
    "payment.subtitle": "Set up recurring card payment",
    "payment.secure": "Secure Payment",
    "payment.secureDesc": "Your card details are encrypted. A digital token verification step will follow.",
    "payment.cardNumber": "Card Number",
    "payment.cardHolder": "Cardholder Name",
    "payment.expiry": "Expiry Date",
    "payment.cvc": "CVC",
    "payment.verifyAndContinue": "Verify & Continue",
    "payment.verifying": "Verifying Card Details",
    "payment.contactingBank": "Contacting your bank to verify card",
    "payment.complete": "complete",
    "payment.digitalToken": "Digital Token Required",
    "payment.digitalTokenDesc": "Open your bank app and approve the verification request, then enter the 6-digit digital token below.",
    "payment.enterToken": "Enter Digital Token",
    "payment.confirmVerification": "Confirm Verification",
    "payment.backToCard": "← Back to card details",
    "payment.saved": "Payment Method Saved",
    "payment.savedDesc": "has been verified and will be charged monthly for your Skim Pintar subscription.",
    "payment.backToDashboard": "Back to Dashboard",
    // Transactions
    "transactions.title": "Transaction History",
    "transactions.subtitle": "View your past payments and records",
    "transactions.noTransactions": "No Transactions",
    "transactions.noTransactionsDesc": "You don't have any transaction records yet.",
    "transactions.monthlyPayment": "Monthly Payment",
    "transactions.refund": "Refund",
    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Masjid Ar-Raudhah",
    "contact.getInTouch": "Get in Touch",
    "contact.getInTouchDesc": "Have a question? Send us a message or reach out via WhatsApp.",
    "contact.name": "Name",
    "contact.email": "Email",
    "contact.message": "Message",
    "contact.namePlaceholder": "Your full name",
    "contact.emailPlaceholder": "your@email.com",
    "contact.messagePlaceholder": "How can we help you?",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.whatsapp": "Chat on WhatsApp",
    "contact.whatsappDesc": "Prefer to chat? Reach us directly on WhatsApp for quick responses.",
    // FAQ
    "faq.title": "FAQ",
    "faq.subtitle": "Frequently Asked Questions",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Customise your experience",
    "settings.appearance": "Appearance",
    "settings.darkMode": "Dark Mode",
    "settings.darkModeDesc": "Switch between light and dark themes",
    "settings.fontSize": "Font Size",
    "settings.fontSizeDesc": "Adjust text size for readability",
    "settings.highContrast": "High Contrast",
    "settings.highContrastDesc": "Increase contrast for better visibility",
    "settings.language": "Language",
    "settings.languageLabel": "Display Language",
    "settings.languageDesc": "Choose your preferred language",
    "settings.notifications": "Notifications",
    "settings.notificationsLabel": "Email Notifications",
    "settings.notificationsDesc": "Receive updates on your application status",
    "settings.saved": "Settings saved",
    "settings.dangerZone": "Danger Zone",
    "settings.deleteAccount": "Delete My Account",
    "settings.deleteAccountDesc": "Permanently delete your account and all associated data. This action cannot be undone.",
    "settings.deleteConfirm": "Are you sure you want to delete your account? All your applications, transaction records, and personal data will be permanently removed. This action cannot be undone.",
    "settings.cancel": "Cancel",
    "settings.yesDelete": "Yes, Delete My Account",
    "settings.deleting": "Deleting...",
    "font.small": "Small",
    "font.medium": "Medium",
    "font.large": "Large",
  },
  ms: {
    "nav.dashboard": "Papan Pemuka",
    "nav.settings": "Tetapan",
    "nav.logout": "Log Keluar",
    "nav.faq": "Soalan Lazim",
    "nav.contactUs": "Hubungi Kami",
    "nav.newApplication": "Permohonan Baru",
    "nav.paymentSetup": "Tetapan Bayaran",
    "nav.trackStatus": "Jejak Status",
    "nav.transactions": "Transaksi",
    "dashboard.welcome": "Assalamualaikum",
    "dashboard.subtitle": "Urus keahlian dan permohonan Skim Pintar anda.",
    "dashboard.yourApplications": "Permohonan Anda",
    "dashboard.noApplications": "Tiada permohonan lagi",
    "dashboard.applyNow": "Mohon Sekarang",
    "dashboard.aboutSkimPintar": "Tentang Skim Pintar",
    "dashboard.applyViaSingpass": "Mohon melalui Singpass",
    "dashboard.setUpCard": "Tetapkan potongan kad",
    "dashboard.viewStatus": "Lihat status permohonan",
    "dashboard.viewPayments": "Lihat sejarah pembayaran",
    "dashboard.cancelApplication": "Batal Permohonan",
    "dashboard.cancelConfirm": "Adakah anda pasti mahu membatalkan permohonan ini? Tindakan ini tidak boleh dibatalkan.",
    "dashboard.keepApplication": "Simpan Permohonan",
    "dashboard.yesCancel": "Ya, Batal",
    "dashboard.cancelling": "Membatalkan...",
    "plan.pintar": "Pintar",
    "plan.pintarPlus": "Pintar Plus",
    "plan.pintarPrice": "Pintar ($5/bulan)",
    "plan.pintarPlusPrice": "Pintar Plus ($20/bulan)",
    "plan.pintarDesc": "Perkhidmatan pengebumian percuma untuk penderma.",
    "plan.pintarPlusDesc": "Perkhidmatan pengebumian percuma untuk penderma dan keluarga terdekat.",
    "plan.recommended": "Disyorkan",
    "plan.benefits": "Manfaat termasuk:",
    "apply.title": "Permohonan Baru",
    "apply.subtitle": "Pendaftaran Skim Pintar",
    "apply.choosePlan": "Pilih Pelan Anda",
    "apply.howRegister": "Bagaimana anda ingin mendaftar?",
    "apply.singpassDesc": "Gunakan Singpass untuk pendaftaran lebih pantas.",
    "apply.loginSingpass": "Log masuk dengan Singpass",
    "apply.autoFill": "Isi butiran anda secara automatik",
    "apply.manualEntry": "Kemasukan Manual",
    "apply.manualDesc": "Isi butiran anda secara manual",
    "apply.connectingSingpass": "Menyambung ke Singpass",
    "apply.retrievingData": "Mendapatkan data MyInfo anda...",
    "apply.myInfoLoaded": "Data MyInfo dimuatkan. Sila sahkan butiran anda.",
    "apply.fillDetails": "Sila isi butiran anda di bawah.",
    "apply.fullName": "Nama Penuh (seperti dalam NRIC)",
    "apply.nric": "Nombor NRIC",
    "apply.dob": "Tarikh Lahir",
    "apply.phone": "Nombor Telefon",
    "apply.email": "E-mel",
    "apply.address": "Alamat",
    "apply.selectedPlan": "Pelan Dipilih",
    "apply.back": "Kembali",
    "apply.submit": "Hantar Permohonan",
    "apply.submitting": "Menghantar...",
    "status.title": "Status Permohonan",
    "status.subtitle": "Jejak permohonan Skim Pintar anda",
    "status.noApplications": "Tiada Permohonan",
    "status.noApplicationsDesc": "Anda belum menghantar sebarang permohonan.",
    "status.submitted": "Dihantar",
    "status.underReview": "Dalam Semakan",
    "status.paymentVerified": "Bayaran Disahkan",
    "status.approved": "Diluluskan",
    "status.rejected": "Ditolak",
    "status.cancelled": "Dibatalkan",
    "status.cancelledOn": "Dibatalkan pada",
    "status.cancelApplication": "Batal Permohonan",
    "payment.title": "Tetapan Bayaran",
    "payment.subtitle": "Tetapkan bayaran kad berulang",
    "payment.secure": "Bayaran Selamat",
    "payment.secureDesc": "Butiran kad anda dienkripsi. Langkah pengesahan token digital akan menyusul.",
    "payment.cardNumber": "Nombor Kad",
    "payment.cardHolder": "Nama Pemegang Kad",
    "payment.expiry": "Tarikh Luput",
    "payment.cvc": "CVC",
    "payment.verifyAndContinue": "Sahkan & Teruskan",
    "payment.verifying": "Mengesahkan Butiran Kad",
    "payment.contactingBank": "Menghubungi bank anda untuk mengesahkan kad",
    "payment.complete": "selesai",
    "payment.digitalToken": "Token Digital Diperlukan",
    "payment.digitalTokenDesc": "Buka aplikasi bank anda dan luluskan permintaan pengesahan, kemudian masukkan token digital 6 digit di bawah.",
    "payment.enterToken": "Masukkan Token Digital",
    "payment.confirmVerification": "Sahkan Pengesahan",
    "payment.backToCard": "← Kembali ke butiran kad",
    "payment.saved": "Kaedah Bayaran Disimpan",
    "payment.savedDesc": "telah disahkan dan akan dicaj bulanan untuk langganan Skim Pintar anda.",
    "payment.backToDashboard": "Kembali ke Papan Pemuka",
    "transactions.title": "Sejarah Transaksi",
    "transactions.subtitle": "Lihat pembayaran dan rekod lepas anda",
    "transactions.noTransactions": "Tiada Transaksi",
    "transactions.noTransactionsDesc": "Anda tidak mempunyai sebarang rekod transaksi.",
    "transactions.monthlyPayment": "Bayaran Bulanan",
    "transactions.refund": "Bayaran Balik",
    "contact.title": "Hubungi Kami",
    "contact.subtitle": "Masjid Ar-Raudhah",
    "contact.getInTouch": "Hubungi Kami",
    "contact.getInTouchDesc": "Ada soalan? Hantar mesej atau hubungi kami melalui WhatsApp.",
    "contact.name": "Nama",
    "contact.email": "E-mel",
    "contact.message": "Mesej",
    "contact.namePlaceholder": "Nama penuh anda",
    "contact.emailPlaceholder": "emel@anda.com",
    "contact.messagePlaceholder": "Bagaimana kami boleh membantu anda?",
    "contact.send": "Hantar Mesej",
    "contact.sending": "Menghantar...",
    "contact.whatsapp": "Sembang di WhatsApp",
    "contact.whatsappDesc": "Lebih suka berbual? Hubungi kami terus di WhatsApp.",
    "faq.title": "Soalan Lazim",
    "faq.subtitle": "Soalan Yang Sering Ditanya",
    "settings.title": "Tetapan",
    "settings.subtitle": "Sesuaikan pengalaman anda",
    "settings.appearance": "Penampilan",
    "settings.darkMode": "Mod Gelap",
    "settings.darkModeDesc": "Tukar antara tema cerah dan gelap",
    "settings.fontSize": "Saiz Font",
    "settings.fontSizeDesc": "Laras saiz teks untuk kebolehbacaan",
    "settings.highContrast": "Kontras Tinggi",
    "settings.highContrastDesc": "Tingkatkan kontras untuk keterlihatan lebih baik",
    "settings.language": "Bahasa",
    "settings.languageLabel": "Bahasa Paparan",
    "settings.languageDesc": "Pilih bahasa pilihan anda",
    "settings.notifications": "Pemberitahuan",
    "settings.notificationsLabel": "Pemberitahuan E-mel",
    "settings.notificationsDesc": "Terima kemas kini tentang status permohonan anda",
    "settings.saved": "Tetapan disimpan",
    "settings.dangerZone": "Zon Bahaya",
    "settings.deleteAccount": "Padam Akaun Saya",
    "settings.deleteAccountDesc": "Padam akaun anda dan semua data berkaitan secara kekal.",
    "settings.deleteConfirm": "Adakah anda pasti mahu memadam akaun anda? Semua permohonan, rekod transaksi, dan data peribadi anda akan dipadamkan secara kekal.",
    "settings.cancel": "Batal",
    "settings.yesDelete": "Ya, Padam Akaun Saya",
    "settings.deleting": "Memadam...",
    "font.small": "Kecil",
    "font.medium": "Sederhana",
    "font.large": "Besar",
  },
  ta: {
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.settings": "அமைப்புகள்",
    "nav.logout": "வெளியேறு",
    "nav.faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "nav.contactUs": "எங்களை தொடர்புகொள்ள",
    "nav.newApplication": "புதிய விண்ணப்பம்",
    "nav.paymentSetup": "கட்டண அமைப்பு",
    "nav.trackStatus": "நிலை கண்காணிப்பு",
    "nav.transactions": "பரிவர்த்தனைகள்",
    "dashboard.welcome": "அஸ்ஸலாமுஅலைக்கும்",
    "dashboard.subtitle": "உங்கள் ஸ்கிம் பிண்டார் உறுப்பினர் மற்றும் விண்ணப்பங்களை நிர்வகிக்கவும்.",
    "dashboard.yourApplications": "உங்கள் விண்ணப்பங்கள்",
    "dashboard.noApplications": "இன்னும் விண்ணப்பங்கள் இல்லை",
    "dashboard.applyNow": "இப்போது விண்ணப்பிக்கவும்",
    "dashboard.aboutSkimPintar": "ஸ்கிம் பிண்டார் பற்றி",
    "dashboard.applyViaSingpass": "Singpass மூலம் விண்ணப்பிக்கவும்",
    "dashboard.setUpCard": "அட்டை கழிப்புகளை அமைக்கவும்",
    "dashboard.viewStatus": "விண்ணப்ப நிலையைக் காணவும்",
    "dashboard.viewPayments": "கட்டண வரலாற்றைக் காணவும்",
    "dashboard.cancelApplication": "விண்ணப்பத்தை ரத்துசெய்",
    "dashboard.cancelConfirm": "இந்த விண்ணப்பத்தை ரத்துசெய்ய விரும்புகிறீர்களா? இது மீட்டமுடியாது.",
    "dashboard.keepApplication": "விண்ணப்பத்தை வைத்திரு",
    "dashboard.yesCancel": "ஆம், ரத்துசெய்",
    "dashboard.cancelling": "ரத்துசெய்கிறது...",
    "plan.pintar": "Pintar",
    "plan.pintarPlus": "Pintar Plus",
    "plan.pintarPrice": "Pintar ($5/மாதம்)",
    "plan.pintarPlusPrice": "Pintar Plus ($20/மாதம்)",
    "plan.pintarDesc": "நன்கொடையாளருக்கு இலவச இறுதி சடங்கு சேவைகள்.",
    "plan.pintarPlusDesc": "நன்கொடையாளர் மற்றும் குடும்பத்திற்கு இலவச இறுதி சடங்கு சேவைகள்.",
    "plan.recommended": "பரிந்துரைக்கப்பட்டது",
    "plan.benefits": "நன்மைகள்:",
    "apply.title": "புதிய விண்ணப்பம்",
    "apply.subtitle": "ஸ்கிம் பிண்டார் பதிவு",
    "apply.choosePlan": "உங்கள் திட்டத்தை தேர்வுசெய்யவும்",
    "apply.howRegister": "எவ்வாறு பதிவு செய்ய விரும்புகிறீர்கள்?",
    "apply.singpassDesc": "விரைவான பதிவிற்கு Singpass பயன்படுத்தவும்.",
    "apply.loginSingpass": "Singpass மூலம் உள்நுழையவும்",
    "apply.autoFill": "MyInfo மூலம் தானாக நிரப்பவும்",
    "apply.manualEntry": "கைமுறை உள்ளீடு",
    "apply.manualDesc": "உங்கள் விவரங்களை கைமுறையாக நிரப்பவும்",
    "apply.connectingSingpass": "Singpass-க்கு இணைக்கிறது",
    "apply.retrievingData": "உங்கள் MyInfo தரவை பெறுகிறது...",
    "apply.myInfoLoaded": "MyInfo தரவு ஏற்றப்பட்டது. உங்கள் விவரங்களை சரிபார்க்கவும்.",
    "apply.fillDetails": "கீழே உங்கள் விவரங்களை நிரப்பவும்.",
    "apply.fullName": "முழு பெயர் (NRIC படி)",
    "apply.nric": "NRIC எண்",
    "apply.dob": "பிறந்த தேதி",
    "apply.phone": "தொலைபேசி எண்",
    "apply.email": "மின்னஞ்சல்",
    "apply.address": "முகவரி",
    "apply.selectedPlan": "தேர்ந்தெடுக்கப்பட்ட திட்டம்",
    "apply.back": "பின்செல்",
    "apply.submit": "விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    "apply.submitting": "சமர்ப்பிக்கிறது...",
    "status.title": "விண்ணப்ப நிலை",
    "status.subtitle": "உங்கள் ஸ்கிம் பிண்டார் விண்ணப்பங்களை கண்காணிக்கவும்",
    "status.noApplications": "விண்ணப்பங்கள் இல்லை",
    "status.noApplicationsDesc": "நீங்கள் இன்னும் எந்த விண்ணப்பமும் சமர்ப்பிக்கவில்லை.",
    "status.submitted": "சமர்ப்பிக்கப்பட்டது",
    "status.underReview": "மதிப்பாய்வில்",
    "status.paymentVerified": "கட்டணம் சரிபார்க்கப்பட்டது",
    "status.approved": "அங்கீகரிக்கப்பட்டது",
    "status.rejected": "நிராகரிக்கப்பட்டது",
    "status.cancelled": "ரத்துசெய்யப்பட்டது",
    "status.cancelledOn": "ரத்துசெய்யப்பட்ட தேதி",
    "status.cancelApplication": "விண்ணப்பத்தை ரத்துசெய்",
    "payment.title": "கட்டண அமைப்பு",
    "payment.subtitle": "மீண்டும் மீண்டும் அட்டை கட்டணத்தை அமைக்கவும்",
    "payment.secure": "பாதுகாப்பான கட்டணம்",
    "payment.secureDesc": "உங்கள் அட்டை விவரங்கள் குறியாக்கம் செய்யப்பட்டுள்ளன.",
    "payment.cardNumber": "அட்டை எண்",
    "payment.cardHolder": "அட்டைதாரர் பெயர்",
    "payment.expiry": "காலாவதி தேதி",
    "payment.cvc": "CVC",
    "payment.verifyAndContinue": "சரிபார்த்து தொடரவும்",
    "payment.verifying": "அட்டை விவரங்களை சரிபார்க்கிறது",
    "payment.contactingBank": "உங்கள் வங்கியை தொடர்புகொள்கிறது",
    "payment.complete": "முடிந்தது",
    "payment.digitalToken": "டிஜிட்டல் டோக்கன் தேவை",
    "payment.digitalTokenDesc": "உங்கள் வங்கி செயலியைத் திறந்து 6 இலக்க டோக்கனை உள்ளிடவும்.",
    "payment.enterToken": "டிஜிட்டல் டோக்கனை உள்ளிடவும்",
    "payment.confirmVerification": "சரிபார்ப்பை உறுதிசெய்",
    "payment.backToCard": "← அட்டை விவரங்களுக்கு திரும்பு",
    "payment.saved": "கட்டண முறை சேமிக்கப்பட்டது",
    "payment.savedDesc": "சரிபார்க்கப்பட்டது மற்றும் மாதாந்திரம் கட்டணம் விதிக்கப்படும்.",
    "payment.backToDashboard": "டாஷ்போர்டுக்கு திரும்பு",
    "transactions.title": "பரிவர்த்தனை வரலாறு",
    "transactions.subtitle": "உங்கள் கடந்த கட்டணங்கள் மற்றும் பதிவுகளை காணவும்",
    "transactions.noTransactions": "பரிவர்த்தனைகள் இல்லை",
    "transactions.noTransactionsDesc": "உங்களிடம் எந்த பரிவர்த்தனை பதிவுகளும் இல்லை.",
    "transactions.monthlyPayment": "மாதாந்திர கட்டணம்",
    "transactions.refund": "திருப்பிச்செலுத்தல்",
    "contact.title": "எங்களை தொடர்புகொள்ள",
    "contact.subtitle": "Masjid Ar-Raudhah",
    "contact.getInTouch": "தொடர்புகொள்ளுங்கள்",
    "contact.getInTouchDesc": "கேள்வி இருக்கிறதா? எங்களுக்கு செய்தி அனுப்பவும்.",
    "contact.name": "பெயர்",
    "contact.email": "மின்னஞ்சல்",
    "contact.message": "செய்தி",
    "contact.namePlaceholder": "உங்கள் முழு பெயர்",
    "contact.emailPlaceholder": "email@unga.com",
    "contact.messagePlaceholder": "நாங்கள் எப்படி உதவ முடியும்?",
    "contact.send": "செய்தி அனுப்பு",
    "contact.sending": "அனுப்புகிறது...",
    "contact.whatsapp": "WhatsApp-இல் அரட்டை",
    "contact.whatsappDesc": "WhatsApp-இல் நேரடியாக எங்களை தொடர்புகொள்ளுங்கள்.",
    "faq.title": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "faq.subtitle": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "உங்கள் அனுபவத்தைத் தனிப்பயனாக்கவும்",
    "settings.appearance": "தோற்றம்",
    "settings.darkMode": "இருண்ட பயன்முறை",
    "settings.darkModeDesc": "ஒளி மற்றும் இருண்ட தீம்களுக்கு இடையே மாறவும்",
    "settings.fontSize": "எழுத்துரு அளவு",
    "settings.fontSizeDesc": "வாசிப்புத்திறனுக்காக உரை அளவை சரிசெய்யவும்",
    "settings.highContrast": "அதிக மாறுபாடு",
    "settings.highContrastDesc": "சிறந்த தெரிவுநிலைக்கு மாறுபாட்டை அதிகரிக்கவும்",
    "settings.language": "மொழி",
    "settings.languageLabel": "காட்சி மொழி",
    "settings.languageDesc": "உங்கள் விருப்பமான மொழியை தேர்ந்தெடுக்கவும்",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.notificationsLabel": "மின்னஞ்சல் அறிவிப்புகள்",
    "settings.notificationsDesc": "உங்கள் விண்ணப்ப நிலை குறித்த புதுப்பிப்புகளைப் பெறவும்",
    "settings.saved": "அமைப்புகள் சேமிக்கப்பட்டன",
    "settings.dangerZone": "ஆபத்து மண்டலம்",
    "settings.deleteAccount": "எனது கணக்கை நீக்கு",
    "settings.deleteAccountDesc": "உங்கள் கணக்கையும் தொடர்புடைய அனைத்து தரவையும் நிரந்தரமாக நீக்கவும்.",
    "settings.deleteConfirm": "உங்கள் கணக்கை நீக்க விரும்புகிறீர்களா? அனைத்து விண்ணப்பங்கள், பரிவர்த்தனை பதிவுகள் நிரந்தரமாக நீக்கப்படும்.",
    "settings.cancel": "ரத்துசெய்",
    "settings.yesDelete": "ஆம், நீக்கு",
    "settings.deleting": "நீக்குகிறது...",
    "font.small": "சிறிய",
    "font.medium": "நடுத்தர",
    "font.large": "பெரிய",
  },
  zh: {
    "nav.dashboard": "仪表板",
    "nav.settings": "设置",
    "nav.logout": "退出",
    "nav.faq": "常见问题",
    "nav.contactUs": "联系我们",
    "nav.newApplication": "新申请",
    "nav.paymentSetup": "付款设置",
    "nav.trackStatus": "跟踪状态",
    "nav.transactions": "交易记录",
    "dashboard.welcome": "Assalamualaikum",
    "dashboard.subtitle": "管理您的 Skim Pintar 会员资格和申请。",
    "dashboard.yourApplications": "您的申请",
    "dashboard.noApplications": "暂无申请",
    "dashboard.applyNow": "立即申请",
    "dashboard.aboutSkimPintar": "关于 Skim Pintar",
    "dashboard.applyViaSingpass": "通过 Singpass 申请",
    "dashboard.setUpCard": "设置卡扣款",
    "dashboard.viewStatus": "查看申请状态",
    "dashboard.viewPayments": "查看付款历史",
    "dashboard.cancelApplication": "取消申请",
    "dashboard.cancelConfirm": "您确定要取消此申请吗？此操作不可撤销。",
    "dashboard.keepApplication": "保留申请",
    "dashboard.yesCancel": "是的，取消",
    "dashboard.cancelling": "取消中...",
    "plan.pintar": "Pintar",
    "plan.pintarPlus": "Pintar Plus",
    "plan.pintarPrice": "Pintar ($5/月)",
    "plan.pintarPlusPrice": "Pintar Plus ($20/月)",
    "plan.pintarDesc": "为捐赠者提供免费葬礼服务。",
    "plan.pintarPlusDesc": "为捐赠者及其直系亲属提供免费葬礼服务。",
    "plan.recommended": "推荐",
    "plan.benefits": "福利包括：",
    "apply.title": "新申请",
    "apply.subtitle": "Skim Pintar 注册",
    "apply.choosePlan": "选择您的计划",
    "apply.howRegister": "您想如何注册？",
    "apply.singpassDesc": "使用 Singpass 更快注册。",
    "apply.loginSingpass": "使用 Singpass 登录",
    "apply.autoFill": "通过 MyInfo 自动填充",
    "apply.manualEntry": "手动输入",
    "apply.manualDesc": "手动填写您的详细信息",
    "apply.connectingSingpass": "正在连接 Singpass",
    "apply.retrievingData": "正在获取您的 MyInfo 数据...",
    "apply.myInfoLoaded": "MyInfo 数据已加载。请验证您的信息。",
    "apply.fillDetails": "请在下方填写您的详细信息。",
    "apply.fullName": "全名（与NRIC一致）",
    "apply.nric": "NRIC 号码",
    "apply.dob": "出生日期",
    "apply.phone": "电话号码",
    "apply.email": "电子邮件",
    "apply.address": "地址",
    "apply.selectedPlan": "已选计划",
    "apply.back": "返回",
    "apply.submit": "提交申请",
    "apply.submitting": "提交中...",
    "status.title": "申请状态",
    "status.subtitle": "跟踪您的 Skim Pintar 申请",
    "status.noApplications": "暂无申请",
    "status.noApplicationsDesc": "您还没有提交任何申请。",
    "status.submitted": "已提交",
    "status.underReview": "审核中",
    "status.paymentVerified": "付款已验证",
    "status.approved": "已批准",
    "status.rejected": "已拒绝",
    "status.cancelled": "已取消",
    "status.cancelledOn": "取消于",
    "status.cancelApplication": "取消申请",
    "payment.title": "付款设置",
    "payment.subtitle": "设置定期卡支付",
    "payment.secure": "安全支付",
    "payment.secureDesc": "您的卡信息已加密。接下来将进行数字令牌验证。",
    "payment.cardNumber": "卡号",
    "payment.cardHolder": "持卡人姓名",
    "payment.expiry": "有效期",
    "payment.cvc": "CVC",
    "payment.verifyAndContinue": "验证并继续",
    "payment.verifying": "正在验证卡信息",
    "payment.contactingBank": "正在联系您的银行验证卡",
    "payment.complete": "完成",
    "payment.digitalToken": "需要数字令牌",
    "payment.digitalTokenDesc": "打开您的银行应用程序，然后输入6位数字令牌。",
    "payment.enterToken": "输入数字令牌",
    "payment.confirmVerification": "确认验证",
    "payment.backToCard": "← 返回卡信息",
    "payment.saved": "付款方式已保存",
    "payment.savedDesc": "已验证，将每月为您的 Skim Pintar 订阅扣款。",
    "payment.backToDashboard": "返回仪表板",
    "transactions.title": "交易历史",
    "transactions.subtitle": "查看您的过去付款和记录",
    "transactions.noTransactions": "暂无交易",
    "transactions.noTransactionsDesc": "您还没有任何交易记录。",
    "transactions.monthlyPayment": "月付款",
    "transactions.refund": "退款",
    "contact.title": "联系我们",
    "contact.subtitle": "Masjid Ar-Raudhah",
    "contact.getInTouch": "联系我们",
    "contact.getInTouchDesc": "有问题？给我们发消息或通过 WhatsApp 联系。",
    "contact.name": "姓名",
    "contact.email": "电子邮件",
    "contact.message": "消息",
    "contact.namePlaceholder": "您的全名",
    "contact.emailPlaceholder": "your@email.com",
    "contact.messagePlaceholder": "我们如何帮助您？",
    "contact.send": "发送消息",
    "contact.sending": "发送中...",
    "contact.whatsapp": "在 WhatsApp 聊天",
    "contact.whatsappDesc": "更喜欢聊天？直接在 WhatsApp 上联系我们。",
    "faq.title": "常见问题",
    "faq.subtitle": "常见问题解答",
    "settings.title": "设置",
    "settings.subtitle": "自定义您的体验",
    "settings.appearance": "外观",
    "settings.darkMode": "深色模式",
    "settings.darkModeDesc": "在浅色和深色主题之间切换",
    "settings.fontSize": "字体大小",
    "settings.fontSizeDesc": "调整文字大小以提高可读性",
    "settings.highContrast": "高对比度",
    "settings.highContrastDesc": "增加对比度以提高可见性",
    "settings.language": "语言",
    "settings.languageLabel": "显示语言",
    "settings.languageDesc": "选择您的首选语言",
    "settings.notifications": "通知",
    "settings.notificationsLabel": "电子邮件通知",
    "settings.notificationsDesc": "接收有关申请状态的更新",
    "settings.saved": "设置已保存",
    "settings.dangerZone": "危险区域",
    "settings.deleteAccount": "删除我的账户",
    "settings.deleteAccountDesc": "永久删除您的账户及所有相关数据。此操作不可撤销。",
    "settings.deleteConfirm": "您确定要删除账户吗？所有申请、交易记录和个人数据将被永久删除。",
    "settings.cancel": "取消",
    "settings.yesDelete": "是的，删除",
    "settings.deleting": "删除中...",
    "font.small": "小",
    "font.medium": "中",
    "font.large": "大",
  },
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider = ({ children }: { children: ReactNode }) => {
  const [settings, setSettings] = useState<Settings>(() => {
    const stored = localStorage.getItem("skim_pintar_settings");
    return stored ? { ...DEFAULT_SETTINGS, ...JSON.parse(stored) } : DEFAULT_SETTINGS;
  });

  useEffect(() => {
    localStorage.setItem("skim_pintar_settings", JSON.stringify(settings));
    document.documentElement.classList.toggle("dark", settings.darkMode);
    const sizeMap: Record<FontSize, string> = { small: "14px", medium: "16px", large: "18px" };
    document.documentElement.style.fontSize = sizeMap[settings.fontSize];
    document.documentElement.classList.toggle("high-contrast", settings.highContrast);
  }, [settings]);

  const updateSettings = (partial: Partial<Settings>) => {
    setSettings((prev) => ({ ...prev, ...partial }));
  };

  const t = (key: string): string => {
    return translations[settings.language]?.[key] || translations.en[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ settings, updateSettings, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context) throw new Error("useSettings must be used within SettingsProvider");
  return context;
};
